### ISSUE TITLE
Is this the source of the I2P Docker Image available from the docker hub account "geti2p"

### ISSUE THREAD

**Issue by eyedeekay** [hkparker/i2p-docker#23]
As you may know there are currently several i2p.i2p containers on the Docker Hub, most of which are out of date. If this is the git repository associated with the docker image associated with the docker hub account geti2p we would like to get in touch with you about maintenance of the docker repository in the future. I2P has now migrated to Git and has a Dockerfile upstream which may be used to build an up-to-date image, and we would like you to consider using it. Please see http://zzz.i2p/topics/3045-does-anybody-know-which-dockerfile-the-official-meeh-i2p-i2p-is-using for more information about it.

**Comment by chris-barry** [comment]
Hey @eyedeekay , send me an email with your DockerHub username and I can add you to the team

**Comment by chris-barry** [comment]
For posterity, this was resolved successfully via email.

**Comment by hkparker** [comment]
Hey.  I don't do a good job of keeping this up to date without a reminder unfortunately, sorry about that.  Just bumped us to the new debian release and latest I2P release.  I don't have access to any of the I2P dockerhub accounts, sounds like @chris-barry was able to assist you there though.  Since there's an official Dockerfile now I can archive this once that's all setup if that's preferred.

**Comment by eyedeekay** [comment]
Thanks for all the help everybody. Looks like the issue should be resolved as soon as I update the site.

**Comment by eyedeekay** [comment]
Site's updated, automated builds are fixed for Java I2P, everything looks good. Closing up.
